# Agent names

names = {"dqn": "DQN",
         "ddqn": "DDQN",
         "dddqn": "DDDQN",
         "dqn_tf": "dqn_tf",
         "ddqn_tf": "ddqn_tf",
         "dddqn_tf": "dddqn_tf",
         "dpg": "DPG",
         "dpg_tf": "dpg",
         "dpg_continuous_tf": "dpg_continuous_tf",
         "ddpg": "DDPG",
         "ddpg_tf": "ddpg_tf",
         "a2c_discrete": "A2C_discrete",
         "a2c_continuous": "A2C_continuous",
         "a2c_discrete_queue": "A2C_discrete_queue",
         "a2c_continuous_queue": "A2C_continuous_queue",
         "a3c_discrete": "A3C_discrete",
         "a3c_continuous": "A3C_continuous",
         "a3c_discrete_tf": "a3c_discrete_tf",
         "ppo_discrete": "PPO_discrete",
         "ppo_continuous": "PPO_continuous",
         "ppo_discrete_multithread": "PPO_discrete_async",
         "ppo_continuous_multithread": "PPO_continuous_async",
         "ppo_s2s_continuous_multithread": "ppo_s2s_continuous_multithread",
         "ppo_transformer_agent_continuous_multithread": "ppo_transformer_agent_continuous_multithread",
         "ppo_transformer_agent_discrete_multithread": "ppo_transformer_agent_discrete_multithread",
         "ppo_continuous_tf": "ppo_continuous_tf",
         "ppo_discrete_tf": "ppo_discrete_tf",
         "ppo_discrete_multithread_tf": "ppo_discrete_multithread_tf",
         "ppo_continuous_multithread_tf": "ppo_continuous_multithread_tf",
         "ppo_continuous_multithread_transformer_tf": "ppo_continuous_multithread_transformer_tf"}
